---
- name: Deploy React App to OCI
  hosts: oci
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
    
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    
    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    
    - name: Add Docker repository
      shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    
    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
      failed_when: docker_version.rc != 0

    - name: Pull latest Docker image
      docker_image:
        name: jeanmichelbb/oci-react
        source: pull
        tag: latest

    - name: Remove existing React app container (if exists)
      docker_container:
        name: react_app_container
        state: absent
        force: yes

    - name: Run React app container
      docker_container:
        name: react_app_container
        image: jeanmichelbb/oci-react:latest
        state: started
        restart_policy: always
        exposed_ports:
          - "80"
        published_ports:
          - "80:80"
        detach: yes