- name: Deploy Docker Compose App to OCI
  hosts: oci
  become: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-compose
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: Copy Docker Compose file to instance
      copy:
        src: docker-compose.yml 
        dest: /opt/app/docker-compose.yml

    - name: Copy .env file for secrets
      copy:
        src: ./.env
        dest: /opt/app/.env

    - name: Stop running containers (if any)
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: absent
      ignore_errors: true

    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: /opt/app
        pull: yes

    - name: Start Docker Compose services
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: present
        recreate: always

    - name: Prune unused Docker images
      command: docker image prune -f

    - name: Create systemd service for Docker Compose
      copy:
        dest: /etc/systemd/system/docker-compose-app.service
        content: |
          [Unit]
          Description=Docker Compose App
          After=network.target
          StartLimitIntervalSec=0

          [Service]
          WorkingDirectory=/opt/app
          ExecStart=/usr/bin/docker compose up -d
          ExecStop=/usr/bin/docker compose down
          Restart=always
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start systemd service
      systemd:
        name: docker-compose-app
        enabled: yes
        state: started
        
    - name: Reload systemd configuration
      command: systemctl daemon-reload