- name: Deploy Docker Containers to OCI
  hosts: oci
  become: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker network
      command: docker network create my_network
      ignore_errors: true  # Ignore if the network already exists

    - name: Remove old MySQL container (if exists)
      command: docker rm -f mysql
      ignore_errors: true

    - name: Run MySQL container
      command: >
        docker run -d --name mysql
        --network my_network
        -e MYSQL_ROOT_PASSWORD=sysadmsysadm
        -e MYSQL_DATABASE=chatbox_db
        -e MYSQL_USER=user
        -e MYSQL_PASSWORD=sysadm
        -v db_data:/var/lib/mysql
        mysql:8

    - name: Remove old Backend container (if exists)
      command: docker rm -f backend
      ignore_errors: true

    - name: Run Backend container
      command: >
        docker run -d --name backend
        --network my_network
        -p 8000:8000
        jeanmichelbb/oci-backend:latest

    - name: Remove old Frontend container (if exists)
      command: docker rm -f frontend
      ignore_errors: true

    - name: Run Frontend container
      command: >
        docker run -d --name frontend
        --network my_network
        -p 80:80
        jeanmichelbb/oci-frontend:latest

    - name: Prune unused Docker images
      command: docker image prune -f

    - name: Create systemd service for Backend
      copy:
        dest: /etc/systemd/system/backend.service
        content: |
          [Unit]
          Description=Backend Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/docker start -a backend
          ExecStop=/usr/bin/docker stop backend
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Create systemd service for Frontend
      copy:
        dest: /etc/systemd/system/frontend.service
        content: |
          [Unit]
          Description=Frontend Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/docker start -a frontend
          ExecStop=/usr/bin/docker stop frontend
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Create systemd service for MySQL
      copy:
        dest: /etc/systemd/system/mysql.service
        content: |
          [Unit]
          Description=MySQL Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/docker start -a mysql
          ExecStop=/usr/bin/docker stop mysql
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start MySQL service
      systemd:
        name: mysql
        enabled: yes
        state: started

    - name: Enable and start Backend service
      systemd:
        name: backend
        enabled: yes
        state: started

    - name: Enable and start Frontend service
      systemd:
        name: frontend
        enabled: yes
        state: started